export type ConfigProviderTheme = "light" | "dark"

export type ConfigProviderBaseThemeVars = {
  black?: string
  blackRgb?: string
  white?: string
  gray1?: string
  gray2?: string
  gray3?: string
  gray4?: string
  gray5?: string
  gray6?: string
  gray7?: string
  gray8?: string
  red?: string
  blue?: string
  cyan?: string
  green?: string
  orange?: string
  orangeDark?: string
  orangeLight?: string
  gradientRed?: string
  gradientOrange?: string
  primaryColor?: string
  infoColor?: string
  successColor?: string
  warningColor?: string
  dangerColor?: string
  textColor?: string
  textColor2?: string
  textColor3?: string
  activeColor?: string
  activeOpacity?: string | number
  disabledOpacity?: string | number
  backgroundColor?: string
  backgroundColor2?: string
  backgroundColorLight?: string
  textLinkColor?: string
  paddingBase?: string
  paddingXs?: string
  paddingSm?: string
  paddingMd?: string
  paddingLg?: string
  paddingXl?: string
  fontSizeXs?: string
  fontSizeSm?: string
  fontSizeMd?: string
  fontSizeLg?: string
  fontWeightBold?: string | number
  lineHeightXs?: string
  lineHeightSm?: string
  lineHeightMd?: string
  lineHeightLg?: string
  baseFontFamily?: string
  priceIntegerFontFamily?: string
  animationDurationBase?: string
  animationDurationFast?: string
  animationTimingFunctionEnter?: string
  animationTimingFunctionExit?: string
  borderColor?: string
  borderWidthBase?: string
  borderRadiusSm?: string
  borderRadiusMd?: string
  borderRadiusLg?: string
  borderRadiusMax?: string
}

export type ConfigProviderThemeVars = ConfigProviderBaseThemeVars &
  import("../action-sheet").ActionSheetThemeVars &
  import("../avatar").AvatarThemeVars &
  import("../back-top").BackTopThemeVars &
  import("../backdrop").BackdropThemeVars &
  import("../badge").BadgeThemeVars &
  import("../button").ButtonThemeVars &
  import("../calendar").CalendarThemeVars &
  import("../cascader").CascaderThemeVars &
  import("../cell").CellThemeVars &
  import("../checkbox").CheckboxThemeVars &
  import("../circle").CircleThemeVars &
  import("../collapse").CollapseThemeVars &
  import("../countdown").CountdownThemeVars &
  import("../dialog").DialogThemeVars &
  import("../divider").DividerThemeVars &
  import("../dropdown-menu").DropdownMenuThemeVars &
  import("../empty").EmptyThemeVars &
  import("../fixed-view").FixedViewThemeVars &
  import("../floating-panel").FloatingPanelThemeVars &
  import("../floating-bubble").FloatingBubbleThemeVars &
  import("../form").FormThemeVars &
  import("../grid").GridThemeVars &
  import("../image").ImageThemeVars &
  import("../index-list").IndexListThemeVars &
  import("../input").InputThemeVars &
  import("../list").ListThemeVars &
  import("../loading").LoadingThemeVars &
  import("../navbar").NavbarThemeVars &
  import("../notice-bar").NoticeBarThemeVars &
  import("../notify").NotifyThemeVars &
  import("../number-keyboard").NumberKeyboardThemeVars &
  import("../pagination").PaginationThemeVars &
  import("../password-input").PasswordInputThemeVars &
  import("../picker").PickerThemeVars &
  import("../popup").PopupThemeVars &
  import("../progress").ProgressThemeVars &
  import("../pull-refresh").PullRefreshThemeVars &
  import("../radio").RadioThemeVars &
  import("../rate").RateThemeVars &
  import("../rolling-text").RollingTextThemeVars &
  import("../search").SearchThemeVars &
  import("../share-sheet").ShareSheetThemeVars &
  import("../sheet").SheetThemeVars &
  import("../sidebar").SidebarThemeVars &
  import("../signature").SignatureThemeVars &
  import("../skeleton").SkeletonThemeVars &
  import("../slider").SliderThemeVars &
  import("../space").SpaceThemeVars &
  import("../stepper").StepperThemeVars &
  import("../steps").StepsThemeVars &
  import("../sticky").StickyThemeVars &
  import("../swiper").SwiperThemeVars &
  import("../switch").SwitchThemeVars &
  import("../tabbar").TabbarThemeVars &
  import("../tabs").TabThemeVars &
  import("../tag").TagThemeVars &
  import("../textarea").TextareaThemeVars &
  import("../timeline").TimelineThemeVars &
  import("../toast").ToastThemeVars &
  import("../tour").TourThemeVars &
  import("../tree-select").TreeSelectThemeVars &
  import("../uploader").UploadThemeVars &
  import("../watermark").WatermarkThemeVars &
  import("../fixed-nav").FixedNavThemeVars
