export type ConfigProviderThemeVars = import("../action-sheet").ActionSheetThemeVars &
  import("../avatar").AvatarThemeVars &
  import("../back-top").BackTopThemeVars &
  import("../backdrop").BackdropThemeVars &
  import("../badge").BadgeThemeVars &
  import("../button").ButtonThemeVars &
  import("../calendar").CalendarThemeVars &
  import("../cascader").CascaderThemeVars &
  import("../cell").CellThemeVars &
  import("../checkbox").CheckboxThemeVars &
  import("../circle").CircleThemeVars &
  import("../collapse").CollapseThemeVars &
  import("../countdown").CountdownThemeVars &
  import("../dialog").DialogThemeVars &
  import("../divider").DividerThemeVars &
  import("../dropdown-menu").DropdownMenuThemeVars &
  import("../empty").EmptyThemeVars &
  import("../fixed-view").FixedViewThemeVars &
  import("../floating-panel").FloatingPanelThemeVars &
  import("../floating-bubble").FloatingBubbleThemeVars &
  import("../form").FormThemeVars &
  import("../grid").GridThemeVars &
  import("../image").ImageThemeVars &
  import("../index-list").IndexListThemeVars &
  import("../input").InputThemeVars &
  import("../list").ListThemeVars &
  import("../loading").LoadingThemeVars &
  import("../navbar").NavbarThemeVars &
  import("../notice-bar").NoticeBarThemeVars &
  import("../notify").NotifyThemeVars &
  import("../number-keyboard").NumberKeyboardThemeVars &
  import("../pagination").PaginationThemeVars &
  import("../password-input").PasswordInputThemeVars &
  import("../picker").PickerThemeVars &
  import("../popup").PopupThemeVars &
  import("../progress").ProgressThemeVars &
  import("../pull-refresh").PullRefreshThemeVars &
  import("../radio").RadioThemeVars &
  import("../rate").RateThemeVars &
  import("../rolling-text").RollingTextThemeVars &
  import("../search").SearchThemeVars &
  import("../share-sheet").ShareSheetThemeVars &
  import("../sheet").SheetThemeVars &
  import("../sidebar").SidebarThemeVars &
  import("../signature").SignatureThemeVars &
  import("../skeleton").SkeletonThemeVars &
  import("../slider").SliderThemeVars &
  import("../space").SpaceThemeVars &
  import("../stepper").StepperThemeVars &
  import("../steps").StepsThemeVars &
  import("../sticky").StickyThemeVars &
  import("../swiper").SwiperThemeVars &
  import("../switch").SwitchThemeVars &
  import("../tabbar").TabbarThemeVars &
  import("../tabs").TabThemeVars &
  import("../tag").TagThemeVars &
  import("../textarea").TextareaThemeVars &
  import("../timeline").TimelineThemeVars &
  import("../toast").ToastThemeVars &
  import("../tree-select").TreeSelectThemeVars &
  import("../uploader").UploadThemeVars &
  import("../watermark").WatermarkThemeVars &
  import("../fixed-nav").FixedNavThemeVars
