name: 🐛 错误报告 Bug Report
description: 如果有什么事情不像预期的那样工作，请告诉我们
title: '🐛 [Bug]:  '
labels: 'bug'
body:
  - type: markdown
    attributes:
      value: |
        ## 感谢您的反馈！
        在提交问题之前，请确保您使用的是所有最新版本 @taroify/* 包，或者优先使用以下方式寻找解决方案：

        - 查看组件文档 [@taroify/core](https://taroify.github.io/taroify.com/introduce)
        - 在 [Issue](https://github.com/mallfoundry/taroify/issues?q=is%3Aissue) 列表中查找解决方案

  - type: dropdown
    id: package
    attributes:
      label: 问题出在哪个包
      description: 选择使用的 Taroify NPM 包名
      options:
        - '@taroify/core'
        - '@taroify/icons'
        - '@taroify/hooks'
        - '@taroify/commerce'
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: 正在使用的 Taroify 版本是多少
      description: 请填写 node_modules/@taroify/core/package.json 里实际安装的版本
      placeholder: 例如：0.7.5
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: 问题出在哪个平台/设备/浏览器
      description: 选择对应的平台/设备/浏览器
      multiple: true
      options:
        - h5
        - weapp
        - alipay
        - tt
        - 其他小程序
    validations:
      required: true

  - type: input
    id: link
    attributes:
      label: 重现链接
      description: |
        请提供一个 **最小化** **可复现** 的代码实例。
        - 最小化：意味着它应该只包含与问题相关的代码与配置，而不是一个庞大的、难以排查问题的仓库。
        - 可复现：这是创建 issue 的基础要求。

        你可以通过 [CodeSandbox](https://codesandbox.io/s/taroify-template-t2fjh) 创建一个可复现实例。

        请不要乱填一个链接，那只会让你的 issue 被直接关闭。
    validations:
      required: true

  - type: textarea
    id: taro
    attributes:
      label: 环境信息
      description: 你可以在项目根目录执行 `taro info`，并将结果粘贴在这里。

  - type: textarea
    id: steps
    attributes:
      label: 重现步骤
      description: |
        简洁清晰的重现步骤能够帮助我们更迅速地定位问题所在。

        请使用 Markdown 语法格式化步骤中涉及的列表、代码片段等，否则它将会非常丑陋。
    validations:
      required: true

  - type: dropdown
    id: fix
    attributes:
      label: 你知道如何解决这个问题吗
      options:
        - 'Yes'
        - 'No'

  - type: dropdown
    id: participate
    attributes:
      label: 您是否愿意参与修复这个问题，并创建一个 PR
      options:
        - 'Yes'
        - 'No'

  - type: textarea
    id: fix_content
    attributes:
      label: 修复这个问题的解决方案
