export { cloneIconComponent, isIconComponent } from "./utils"
export { default as Arrow } from "./Arrow"
export { default as ArrowDown } from "./ArrowDown"
export { default as ArrowLeft } from "./ArrowLeft"
export { default as ArrowRight } from "./ArrowRight"
export { default as ArrowUp } from "./ArrowUp"
export { default as Cross } from "./Cross"
export { default as Down } from "./Down"
export { default as Fail } from "./Fail"
export { default as FriendsOutlined } from "./FriendsOutlined"
export { default as HomeOutlined } from "./HomeOutlined"
export { default as LocationOutlined } from "./LocationOutlined"
export { default as Photo } from "./Photo"
export { default as PhotoFail } from "./PhotoFail"
export { default as Search } from "./Search"
export { default as SettingOutlined } from "./SettingOutlined"
export { default as ShopOutlined } from "./ShopOutlined"
export { default as Success } from "./Success"
