name: Deploy Site

on:
  push:
    tags:
      - 'v*'

concurrency:
  group: deploy-site-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NODE_VERSION: "20.18.1"

jobs:
  build-and-deploy:
    if: github.repository == 'mallfoundry/taroify'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: yarn

      - name: Run Build Site
        run: |
          yarn install --frozen-lockfile
          yarn run build:www

      - name: Deploy for GitHub 🚀
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          branch: gh-pages
          folder: bundles/www
          token: ${{ secrets.TAROIFY_SITE_TOKEN }}
          repository-name: taroify/taroify.com
          single-commit: true
          clean: true
