name: Close Issue

on:
  schedule:
    - cron: "0 2 * * 1"
  workflow_dispatch: # Allow for running this manually.

permissions:
  actions: write
  issues: write

jobs:
  issue-to-be-closed:
    if: github.repository == 'taroify/taroify'
    runs-on: ubuntu-latest
    steps:
      - name: close-issues
        uses: actions/stale@v10
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          stale-issue-label: 'to be closed'
          days-before-issue-stale: -1
          days-before-issue-close: 7
          days-before-pr-stale: -1
          days-before-pr-close: -1
          remove-issue-stale-when-updated: false
          close-issue-reason: 'completed'
