name: CI

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/**"

  push:
    branches:
      - main
    tags:
      - "v*"
    paths-ignore:
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/**"

  workflow_dispatch:

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

env:
  NODE_VERSION: "20.18.1"

jobs:
  lint:
    if: github.repository == 'mallfoundry/taroify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Run linter
        run: yarn run lint

  test:
    if: github.repository == 'mallfoundry/taroify'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn run build:packages

      - name: Run test cases
        run: yarn run test:coverage --watchman=false

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: ./coverage
